// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.zlikun.learning.proto;

public final class UserInfo {
  private UserInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.zlikun.learning.proto.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MALE = 0;</code>
     */
    MALE(0),
    /**
     * <code>FEMALE = 1;</code>
     */
    FEMALE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MALE = 0;</code>
     */
    public static final int MALE_VALUE = 0;
    /**
     * <code>FEMALE = 1;</code>
     */
    public static final int FEMALE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return MALE;
        case 1: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zlikun.learning.proto.UserInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zlikun.learning.proto.Gender)
  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zlikun.learning.proto.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.com.zlikun.learning.proto.Gender gender = 3;</code>
     */
    int getGenderValue();
    /**
     * <code>.com.zlikun.learning.proto.Gender gender = 3;</code>
     */
    com.zlikun.learning.proto.UserInfo.Gender getGender();

    /**
     * <pre>
     * 兴趣爱好，数组结构
     * </pre>
     *
     * <code>repeated string hobbies = 4;</code>
     */
    java.util.List<java.lang.String>
        getHobbiesList();
    /**
     * <pre>
     * 兴趣爱好，数组结构
     * </pre>
     *
     * <code>repeated string hobbies = 4;</code>
     */
    int getHobbiesCount();
    /**
     * <pre>
     * 兴趣爱好，数组结构
     * </pre>
     *
     * <code>repeated string hobbies = 4;</code>
     */
    java.lang.String getHobbies(int index);
    /**
     * <pre>
     * 兴趣爱好，数组结构
     * </pre>
     *
     * <code>repeated string hobbies = 4;</code>
     */
    com.google.protobuf.ByteString
        getHobbiesBytes(int index);

    /**
     * <pre>
     * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; socials = 5;</code>
     */
    int getSocialsCount();
    /**
     * <pre>
     * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; socials = 5;</code>
     */
    boolean containsSocials(
        java.lang.String key);
    /**
     * Use {@link #getSocialsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getSocials();
    /**
     * <pre>
     * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; socials = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getSocialsMap();
    /**
     * <pre>
     * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; socials = 5;</code>
     */

    java.lang.String getSocialsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; socials = 5;</code>
     */

    java.lang.String getSocialsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.zlikun.learning.proto.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zlikun.learning.proto.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      id_ = 0L;
      name_ = "";
      gender_ = 0;
      hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              gender_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                hobbies_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              hobbies_.add(s);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                socials_ = com.google.protobuf.MapField.newMapField(
                    SocialsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              socials__ = input.readMessage(
                  SocialsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              socials_.getMutableMap().put(
                  socials__.getKey(), socials__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          hobbies_ = hobbies_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zlikun.learning.proto.UserInfo.internal_static_com_zlikun_learning_proto_User_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetSocials();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zlikun.learning.proto.UserInfo.internal_static_com_zlikun_learning_proto_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zlikun.learning.proto.UserInfo.User.class, com.zlikun.learning.proto.UserInfo.User.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 3;
    private int gender_;
    /**
     * <code>.com.zlikun.learning.proto.Gender gender = 3;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.com.zlikun.learning.proto.Gender gender = 3;</code>
     */
    public com.zlikun.learning.proto.UserInfo.Gender getGender() {
      com.zlikun.learning.proto.UserInfo.Gender result = com.zlikun.learning.proto.UserInfo.Gender.valueOf(gender_);
      return result == null ? com.zlikun.learning.proto.UserInfo.Gender.UNRECOGNIZED : result;
    }

    public static final int HOBBIES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList hobbies_;
    /**
     * <pre>
     * 兴趣爱好，数组结构
     * </pre>
     *
     * <code>repeated string hobbies = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHobbiesList() {
      return hobbies_;
    }
    /**
     * <pre>
     * 兴趣爱好，数组结构
     * </pre>
     *
     * <code>repeated string hobbies = 4;</code>
     */
    public int getHobbiesCount() {
      return hobbies_.size();
    }
    /**
     * <pre>
     * 兴趣爱好，数组结构
     * </pre>
     *
     * <code>repeated string hobbies = 4;</code>
     */
    public java.lang.String getHobbies(int index) {
      return hobbies_.get(index);
    }
    /**
     * <pre>
     * 兴趣爱好，数组结构
     * </pre>
     *
     * <code>repeated string hobbies = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHobbiesBytes(int index) {
      return hobbies_.getByteString(index);
    }

    public static final int SOCIALS_FIELD_NUMBER = 5;
    private static final class SocialsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.zlikun.learning.proto.UserInfo.internal_static_com_zlikun_learning_proto_User_SocialsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> socials_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetSocials() {
      if (socials_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SocialsDefaultEntryHolder.defaultEntry);
      }
      return socials_;
    }

    public int getSocialsCount() {
      return internalGetSocials().getMap().size();
    }
    /**
     * <pre>
     * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; socials = 5;</code>
     */

    public boolean containsSocials(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetSocials().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSocialsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSocials() {
      return getSocialsMap();
    }
    /**
     * <pre>
     * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; socials = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getSocialsMap() {
      return internalGetSocials().getMap();
    }
    /**
     * <pre>
     * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; socials = 5;</code>
     */

    public java.lang.String getSocialsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSocials().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; socials = 5;</code>
     */

    public java.lang.String getSocialsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSocials().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (gender_ != com.zlikun.learning.proto.UserInfo.Gender.MALE.getNumber()) {
        output.writeEnum(3, gender_);
      }
      for (int i = 0; i < hobbies_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hobbies_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetSocials(),
          SocialsDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (gender_ != com.zlikun.learning.proto.UserInfo.Gender.MALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, gender_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hobbies_.size(); i++) {
          dataSize += computeStringSizeNoTag(hobbies_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHobbiesList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetSocials().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        socials__ = SocialsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, socials__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zlikun.learning.proto.UserInfo.User)) {
        return super.equals(obj);
      }
      com.zlikun.learning.proto.UserInfo.User other = (com.zlikun.learning.proto.UserInfo.User) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && gender_ == other.gender_;
      result = result && getHobbiesList()
          .equals(other.getHobbiesList());
      result = result && internalGetSocials().equals(
          other.internalGetSocials());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      if (getHobbiesCount() > 0) {
        hash = (37 * hash) + HOBBIES_FIELD_NUMBER;
        hash = (53 * hash) + getHobbiesList().hashCode();
      }
      if (!internalGetSocials().getMap().isEmpty()) {
        hash = (37 * hash) + SOCIALS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetSocials().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zlikun.learning.proto.UserInfo.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zlikun.learning.proto.UserInfo.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zlikun.learning.proto.UserInfo.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zlikun.learning.proto.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zlikun.learning.proto.User)
        com.zlikun.learning.proto.UserInfo.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zlikun.learning.proto.UserInfo.internal_static_com_zlikun_learning_proto_User_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetSocials();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableSocials();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zlikun.learning.proto.UserInfo.internal_static_com_zlikun_learning_proto_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zlikun.learning.proto.UserInfo.User.class, com.zlikun.learning.proto.UserInfo.User.Builder.class);
      }

      // Construct using com.zlikun.learning.proto.UserInfo.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        gender_ = 0;

        hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableSocials().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zlikun.learning.proto.UserInfo.internal_static_com_zlikun_learning_proto_User_descriptor;
      }

      public com.zlikun.learning.proto.UserInfo.User getDefaultInstanceForType() {
        return com.zlikun.learning.proto.UserInfo.User.getDefaultInstance();
      }

      public com.zlikun.learning.proto.UserInfo.User build() {
        com.zlikun.learning.proto.UserInfo.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zlikun.learning.proto.UserInfo.User buildPartial() {
        com.zlikun.learning.proto.UserInfo.User result = new com.zlikun.learning.proto.UserInfo.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.gender_ = gender_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          hobbies_ = hobbies_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.hobbies_ = hobbies_;
        result.socials_ = internalGetSocials();
        result.socials_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zlikun.learning.proto.UserInfo.User) {
          return mergeFrom((com.zlikun.learning.proto.UserInfo.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zlikun.learning.proto.UserInfo.User other) {
        if (other == com.zlikun.learning.proto.UserInfo.User.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (!other.hobbies_.isEmpty()) {
          if (hobbies_.isEmpty()) {
            hobbies_ = other.hobbies_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureHobbiesIsMutable();
            hobbies_.addAll(other.hobbies_);
          }
          onChanged();
        }
        internalGetMutableSocials().mergeFrom(
            other.internalGetSocials());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zlikun.learning.proto.UserInfo.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zlikun.learning.proto.UserInfo.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <code>.com.zlikun.learning.proto.Gender gender = 3;</code>
       */
      public int getGenderValue() {
        return gender_;
      }
      /**
       * <code>.com.zlikun.learning.proto.Gender gender = 3;</code>
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.zlikun.learning.proto.Gender gender = 3;</code>
       */
      public com.zlikun.learning.proto.UserInfo.Gender getGender() {
        com.zlikun.learning.proto.UserInfo.Gender result = com.zlikun.learning.proto.UserInfo.Gender.valueOf(gender_);
        return result == null ? com.zlikun.learning.proto.UserInfo.Gender.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.zlikun.learning.proto.Gender gender = 3;</code>
       */
      public Builder setGender(com.zlikun.learning.proto.UserInfo.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.zlikun.learning.proto.Gender gender = 3;</code>
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHobbiesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          hobbies_ = new com.google.protobuf.LazyStringArrayList(hobbies_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       * 兴趣爱好，数组结构
       * </pre>
       *
       * <code>repeated string hobbies = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHobbiesList() {
        return hobbies_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 兴趣爱好，数组结构
       * </pre>
       *
       * <code>repeated string hobbies = 4;</code>
       */
      public int getHobbiesCount() {
        return hobbies_.size();
      }
      /**
       * <pre>
       * 兴趣爱好，数组结构
       * </pre>
       *
       * <code>repeated string hobbies = 4;</code>
       */
      public java.lang.String getHobbies(int index) {
        return hobbies_.get(index);
      }
      /**
       * <pre>
       * 兴趣爱好，数组结构
       * </pre>
       *
       * <code>repeated string hobbies = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHobbiesBytes(int index) {
        return hobbies_.getByteString(index);
      }
      /**
       * <pre>
       * 兴趣爱好，数组结构
       * </pre>
       *
       * <code>repeated string hobbies = 4;</code>
       */
      public Builder setHobbies(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbiesIsMutable();
        hobbies_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 兴趣爱好，数组结构
       * </pre>
       *
       * <code>repeated string hobbies = 4;</code>
       */
      public Builder addHobbies(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbiesIsMutable();
        hobbies_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 兴趣爱好，数组结构
       * </pre>
       *
       * <code>repeated string hobbies = 4;</code>
       */
      public Builder addAllHobbies(
          java.lang.Iterable<java.lang.String> values) {
        ensureHobbiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hobbies_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 兴趣爱好，数组结构
       * </pre>
       *
       * <code>repeated string hobbies = 4;</code>
       */
      public Builder clearHobbies() {
        hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 兴趣爱好，数组结构
       * </pre>
       *
       * <code>repeated string hobbies = 4;</code>
       */
      public Builder addHobbiesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureHobbiesIsMutable();
        hobbies_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> socials_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetSocials() {
        if (socials_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SocialsDefaultEntryHolder.defaultEntry);
        }
        return socials_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableSocials() {
        onChanged();;
        if (socials_ == null) {
          socials_ = com.google.protobuf.MapField.newMapField(
              SocialsDefaultEntryHolder.defaultEntry);
        }
        if (!socials_.isMutable()) {
          socials_ = socials_.copy();
        }
        return socials_;
      }

      public int getSocialsCount() {
        return internalGetSocials().getMap().size();
      }
      /**
       * <pre>
       * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; socials = 5;</code>
       */

      public boolean containsSocials(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetSocials().getMap().containsKey(key);
      }
      /**
       * Use {@link #getSocialsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getSocials() {
        return getSocialsMap();
      }
      /**
       * <pre>
       * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; socials = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getSocialsMap() {
        return internalGetSocials().getMap();
      }
      /**
       * <pre>
       * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; socials = 5;</code>
       */

      public java.lang.String getSocialsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetSocials().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; socials = 5;</code>
       */

      public java.lang.String getSocialsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetSocials().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearSocials() {
        internalGetMutableSocials().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; socials = 5;</code>
       */

      public Builder removeSocials(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableSocials().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableSocials() {
        return internalGetMutableSocials().getMutableMap();
      }
      /**
       * <pre>
       * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; socials = 5;</code>
       */
      public Builder putSocials(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableSocials().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * 社交帐号，映射结构：&lt;平台名称, 平台帐号&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; socials = 5;</code>
       */

      public Builder putAllSocials(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableSocials().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zlikun.learning.proto.User)
    }

    // @@protoc_insertion_point(class_scope:com.zlikun.learning.proto.User)
    private static final com.zlikun.learning.proto.UserInfo.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zlikun.learning.proto.UserInfo.User();
    }

    public static com.zlikun.learning.proto.UserInfo.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.zlikun.learning.proto.UserInfo.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zlikun_learning_proto_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zlikun_learning_proto_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zlikun_learning_proto_User_SocialsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zlikun_learning_proto_User_SocialsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\031com.zlikun.learning.proto\"" +
      "\323\001\n\004User\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\0221\n\006ge" +
      "nder\030\003 \001(\0162!.com.zlikun.learning.proto.G" +
      "ender\022\017\n\007hobbies\030\004 \003(\t\022=\n\007socials\030\005 \003(\0132" +
      ",.com.zlikun.learning.proto.User.Socials" +
      "Entry\032.\n\014SocialsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001*\036\n\006Gender\022\010\n\004MALE\020\000\022\n\n\006FEM" +
      "ALE\020\001B\nB\010UserInfob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zlikun_learning_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zlikun_learning_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zlikun_learning_proto_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Gender", "Hobbies", "Socials", });
    internal_static_com_zlikun_learning_proto_User_SocialsEntry_descriptor =
      internal_static_com_zlikun_learning_proto_User_descriptor.getNestedTypes().get(0);
    internal_static_com_zlikun_learning_proto_User_SocialsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zlikun_learning_proto_User_SocialsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
